common/common/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('library_management.urls')),
    path('admin/', admin.site.urls),
]

common/library_management/urls.py
from django.urls import path
from django.urls import include

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('book/<uuid:pk>/borrow', views.borrow_book, name='borrow'),
    path('book/<int:pk>/review/', views.review_book, name='book-review'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', views.auth_login, name='auth-login'),
    path('accounts/profile/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
]

common/library_management/models/author.py
from django.db import models


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(
        null=True,
        blank=True
    )
    date_of_death = models.DateField(
        'Died',
        null=True, blank=True
    )

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return f'{self.last_name} {self.first_name} {self.middle_name}'

common/library_management/models/book.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from .review import Review
from .genre import Genre


class Book(models.Model):
    isbn = models.CharField(
        'ISBN',
        max_length=13,
        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>'
    )
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        'Author',
        on_delete=models.SET_NULL,
        null=True
    )
    summary = models.TextField(
        max_length=1000,
        help_text='Enter a brief description of the book'
    )
    genre = models.ManyToManyField(
        Genre,
        help_text='Select a genre for this book'
    )
    reviews = models.ManyToManyField(
        Review,
        help_text='Leave a review for this book'
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    def display_review(self):
        return ', '.join(reviews.review + ' - ' + reviews.reviewer.username for reviews in self.reviews.all()[:3])


class BookInstance(models.Model):
    BOOK_STATUS = (
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text='Unique ID for this particular book across whole library'
    )
    book = models.ForeignKey(
        'Book',
        on_delete=models.CASCADE,
        null=True
    )
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(
        null=True,
        blank=True
    )
    borrower = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    status = models.CharField(
        max_length=1,
        choices=BOOK_STATUS,
        blank=True,
        default='a',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return f'{self.id} ({self.book.title})'

common/library_management/models/genre.py
from django.db import models


class Genre(models.Model):
    name = models.CharField(
        max_length=200,
        help_text='Enter a book genre (e.g. Science Fiction)'
    )

    def __str__(self):
        return self.name

common/library_management/models/review.py
from django.contrib.auth.models import User
from django.db import models


class Review(models.Model):
    review = models.CharField(
        max_length=1000,
        help_text='Enter your review'
    )
    reviewer = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )

    def get_reviewer(self):
        return self.reviewer.name

    def __str__(self):
        return self.review

common/library_management/forms.py
import datetime

from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError
from django import forms


class ReviewForm(forms.Form):
    review = forms.CharField(max_length=1000, help_text='Оставьте свой отзыв для этой книги')

    def clean_review(self):
        data = self.cleaned_data['review']

        if data == '':
            raise ValidationError('Не оставляйте это поле пустым')

        return data


class RegistrationForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100, help_text='Введите ваше имя', widget=forms.TextInput(attrs={'class': 'input'}))
    last_name = forms.CharField(max_length=100, help_text='Введите вашу фамилию',
                                widget=forms.TextInput(attrs={'class': 'input'}))
    username = forms.CharField(max_length=100, help_text='Введите username',
                               widget=forms.TextInput(attrs={'class': 'input'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}),
                                       help_text='Повторите пароль')
    email = forms.EmailField(help_text='Введите вашу эл. почту', widget=forms.TextInput(attrs={'class': 'input'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'confirm_password')


class MyAuthenticationForm(AuthenticationForm):
    username = forms.CharField(label='Username', max_length=30, widget=forms.TextInput(attrs={'class': 'input'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'input'}))

    def __init__(self, *args, **kwargs):
        super(MyAuthenticationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'input'

    def confirm_login_allowed(self, user):
        if not user:
            raise forms.ValidationError('Пользователь не найден')
        elif not user.is_active or not user.is_validated:
            raise forms.ValidationError('Была проблема с твоим логином', code='invalid_login')


class BorrowBookForm(forms.Form):
    due_date = forms.DateField(help_text='Введите дату возврата')

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError('Недействительная дата - обновление в прошлом')
        return data


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text='Введите дату между сегодняшним днем и 4 неделями (по умолчанию 3)')

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError('Недействительная дата - обновление в прошлом')

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError('Недействительная дата - продление более чем на 4 недели вперед.')

        return data

common/library_management/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.views.decorators.csrf import csrf_protect
from django.views.generic import ListView, DetailView

from .forms import MyAuthenticationForm, RegistrationForm, ReviewForm, BorrowBookForm, RenewBookForm
from .models import Book, Author, BookInstance, Review
import datetime
from django.contrib.auth.models import Group


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
    }

    return render(request, 'index.html', context=context)


class BookListView(LoginRequiredMixin, ListView):
    model = Book
    paginate_by = 1


class BookDetailView(LoginRequiredMixin, DetailView):
    model = Book


@csrf_protect
def auth_login(request):
    if request.method == 'POST':
        loginform = MyAuthenticationForm(request.POST)
        signupform = RegistrationForm(request.POST)
        if 'login' in request.POST:
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request=request, username=username, password=password)

            if user is not None:
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                return redirect('books')
            else:
                render(request, 'registration/login.html', {'error': 'Wrong credentials'})
        elif signupform.is_valid() and 'sign-up' in request.POST:
            # Saving user to the database
            user = signupform.save()
            user.refresh_from_db()
            raw_password = signupform.cleaned_data.get('password')
            user.set_password(raw_password)
            user.save()

            # Automatically signing the user up
            raw_password = signupform.cleaned_data.get('password')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')

            # NEED ADD GROUP
            # group = Group.objects.get(name='Student/Teacher')
            # group.user_set.add(user)

            return redirect('books')
    else:
        loginform = MyAuthenticationForm()
        signupform = RegistrationForm()

    return render(request, 'registration/login.html', {'loginform': loginform, 'signupform': signupform})


def review_book(request, pk):
    book = get_object_or_404(Book, pk=pk)

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review_text = form.cleaned_data['review']
            reviewer = request.user
            review = Review(review=review_text, reviewer=reviewer)
            review.save()
            book.reviews.add(review)
            book.save()
            return redirect('books')
    else:
        form = ReviewForm()
    context = {
        'form': form,
        'book': book,
    }
    return render(request, 'library_management/review_book.html', context)


def profile(request):
    bookinstance = BookInstance.objects.all()
    booksreviewed = Book.objects.all()

    context = {
        'bookinstance': bookinstance,
        'booksreviewed': booksreviewed,
    }

    return render(request, 'profile.html', context=context)


def borrow_book(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':

        form = BorrowBookForm(request.POST)

        if form.is_valid():
            due_date = form.cleaned_data['due_date']
            book_instance.borrower = request.user
            book_instance.due_back = due_date
            book_instance.status = 'r'

            book_instance.save()

            return redirect('profile')

    else:
        form = BorrowBookForm(initial={'due_date': datetime.date.today()})

    context = {
        'form': form,
        'book_instance': book_instance
    }

    return render(request, 'library_management/borrow_book.html', context)


def return_book(request, pk):
    # РЕАЛИЗАЦИЯ НА БУДУЖЕЕ
    pass

def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':
        form = RenewBookForm(request.POST)

        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()
            return redirect('index')

    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'library_management/book_renew_librarian.html', context)


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'library_management/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(
            borrower=self.request.user
        ).filter(status__exact='r').order_by('due_back')
git clone https://vorofikini@bitbucket.org/vorofikini/hola.git

def about(request):
    return render(request, 'library_management/about.html', {})

common/library_management/templates/library_management/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <h1>О проекте</h1>
    <div class="row">
        <div class="five columns">
            <img src="{% static 'images/no-image.jpg' %}" width="400">
        </div>
        <div class="seven columns">
            <h3>Привет, меня зовут Ярослав Никифоров</h3>
            <p>
                Я разработчик данного проекта
                ...
            </p>
        </div>
    </div>
</div>

{% endblock %}

common/library_management/templates/library_management/book_detail.html
{% extends "base.html" %}
{% load static %}
{
{% block content %}
<div class="container">
  <h1>{{ book.title }}, <a href="{% url 'book-review' book.id %}" style="font-size:16px;">оставить отзыв</a></h1>
  <div class="row">
    <div class="five columns">
      <img src="{% static 'images/no-image.jpg' %}">
    </div>
    <div class="seven columns">
      <p><b>Автор:</b><br>{{ book.author }}</p>
      <p><b>Описание:</b><br>{{ book.summary }}</p>
      <p><b>ISBN:</b><br>{{ book.isbn }}</p>
      <p><b>Жанр:</b><br>{{ book.genre.all|join:", " }}</p> <br>
    </div>
  </div>


  <div class="row">
    <h2>Отзывы</h2>
    {% for b in book.reviews.all %}
      <p>Пользователь: {{ b.reviewer }}<br>{{ b.review }}</p>
      <br>
    {% endfor %}
  </div>

  <div class="row">
    <h2>Книги на руках</h2>
    {% for copy in book.bookinstance_set.all %}
    <p>Статус: {{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}
      <p><strong>Должна быть возвращена:</strong> {{ copy.due_back }}</p>
    {% else %}
      <p><a href="{% url 'borrow' copy.id %}">Зарезервировать</a></p>
    {% endif %}
      <p class="text-muted"><strong>ID:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>

</div>
{% endblock %}

common/library_management/templates/library_management/book_list.html
{% extends "base.html" %}
{% block a %}{% endblock %}
{% block content %}
<div class="content">
    <h1>Список книг</h1>
    <div class="row">
        <div class="twelve">
            <div class="card" style="width: 18rem;">
                <div class="card-body">

                    {% if not user.is_authenticated or perms.catalog.view_book %}
                       {% if book_list %}

                               {% for book in book_list %}
                               <img class="card-img-top" src="..." alt="Card image cap">  <!-- для картинки -->
                               <li><h5 class="card-title">{{ book.title }}</h5> ({{book.author}})</li>
                               <a href="{{ book.get_absolute_url }}" class="btn btn-primary">Подробнее</a>
                               {% endfor %}

                    {% else %}
                    <p>Книг нет в наличии.</p>
                    {% endif %}
                </div>
            </div>
                {% block pagination %}
                    {% if is_paginated %}
                    <div class="pagination">
                        <span class="page-links">
                            {% if page_obj.has_previous %}
                            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                            {% endif %}
                            <span class="page-current">
                                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                            </span>
                            {% if page_obj.has_next %}
                            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                            {% endif %}
                        </span>
                    </div>
                    {% endif %}
                {% endblock %}
            {% else %}
            <p>У вас нет доступа для просмотра этой страницы. Пожалуйста авторизуйтесь.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Название карточки</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Переход куда-нибудь</a>
  </div>
</div>

common/library_management/templates/library_management/book_renew_librarian.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row">
      <h1>Продлить аренду книги, {{ book_instance.book.title }}</h1>
      <form action="" method="post">
      {% csrf_token %}
        <form method="post" action="">
            {% csrf_token %}
            {{ form.renewal_date.label_tag }}
            {{ form.renewal_date }}
            <br>
            <input type="submit" value="Продлить">
        </form>
    </form>
    </div>
</div>
 
{% endblock %}

common/library_management/templates/library_management/bookinstance_list_borrowed_user.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>Список моих книг</h1>
    {% if bookinstance_list %}
    <div class="row">
        <ul>
            {% for bookinst in bookinstance_list %}
            <li>
                <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a>
                ({{ bookinst.due_back }})
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
</div>
{% endblock %}

common/library_management/templates/library_management/borrow_book.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <h1>Зарезервировать книгу, {{ book_instance.book.title }}</h1>

        <form method="post" action="">
            {% csrf_token %}
            {{ form.due_date.label_tag }}
            {{ form.due_date }}
            <br>
            <input type="submit" value="Забронировать">
        </form>
    </div>
</div>

{% endblock %}

common/library_management/templates/library_management/review_book.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1>Оставить отзыв на книгу, {{ book.title }}</h1>
  <form action="" method="post">
    {% csrf_token %}
    <div class="row">
      <div class="six columns">
        <label>Ваше сообщение:</label>
        {{form.review}}
        <input type="submit" value="Отправить">
      </div>
    </div>
  </form>
</div>
{% endblock %}